# Importar bibliotecas e carregar os dados

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
import os

#df = pd.read_csv("../data/world_happiness_report.csv")
#df.head()

In [26]:

# Download latest version
origem = kagglehub.dataset_download("usamabuttar/world-happiness-report-2005-present")

print("Path to dataset files:", origem)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.10), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\felip\.cache\kagglehub\datasets\usamabuttar\world-happiness-report-2005-present\versions\1

In [27]:
os.makedirs("../data/processed", exist_ok=True)

In [28]:
from pathlib import Path

origem = Path(origem)
destino = Path('../data')
destino.mkdir(parents=True, exist_ok=True)

for arquivo in origem.iterdir():
   if arquivo.is_file():
      arquivo.replace(destino / arquivo.name)

In [29]:
df = pd.read_csv('../data/World Happiness Report.csv')
df

,Country Name,Regional Indicator,Year,Life Ladder,Log GDP Per Capita,Social Support,Healthy Life Expectancy At Birth,Freedom To Make Life Choices,Generosity,Perceptions Of Corruption,Positive Affect,Negative Affect,Confidence In National Government
0,Afghanistan,South Asia,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,South Asia,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,South Asia,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,South Asia,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,South Asia,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,Sub-Saharan Africa,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,Sub-Saharan Africa,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,Sub-Saharan Africa,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,Sub-Saharan Africa,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,Sub-Saharan Africa,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,NaN

In [30]:
df.isna().sum()

Country Name                           0
Regional Indicator                   112
Year                                   0
Life Ladder                            0
Log GDP Per Capita                    20
Social Support                        13
Healthy Life Expectancy At Birth      54
Freedom To Make Life Choices          33
Generosity                            73
Perceptions Of Corruption            116
Positive Affect                       24
Negative Affect                       16
Confidence In National Government    361
dtype: int64

# Traduzindo colunas

In [31]:
from googletrans import Translator

translator = Translator()
colunas_traduzidas = {}

for col in df.columns:
   try:
      traducao = translator.translate(col, src='en', dest='pt').text
      colunas_traduzidas[col] = traducao
   except Exception:
      colunas_traduzidas[col] = col

df = df.rename(columns=colunas_traduzidas)

print("Colunas traduzidas:")
print(df.columns.tolist())

# Salvar o CSV traduzido
df.to_csv('../data/processed/world_happiness_report_colunas_pt.csv', index=False)

Colunas traduzidas:
['Nome do país', 'Indicador Regional', 'Ano', 'Escada da Vida', 'Registrar PIB per capita', 'Apoio Social', 'Expectativa de vida saudável ao nascer', 'Liberdade para fazer escolhas de vida', 'Generosidade', 'Percepções de corrupção', 'Afeto Positivo', 'Afeto Negativo', 'Confiança no governo nacional']

# Analisando o Dataset traduzido

In [32]:
df_2 = df.copy()
df_2.info()
df_2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2199 entries, 0 to 2198
Data columns (total 13 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Nome do país                            2199 non-null   object
 1   Indicador Regional                      2087 non-null   object
 2   Ano                                     2199 non-null   int64
 3   Escada da Vida                          2199 non-null   float64
 4   Registrar PIB per capita                2179 non-null   float64
 5   Apoio Social                            2186 non-null   float64
 6   Expectativa de vida saudável ao nascer  2145 non-null   float64
 7   Liberdade para fazer escolhas de vida   2166 non-null   float64
 8   Generosidade                            2126 non-null   float64
 9   Percepções de corrupção                 2083 non-null   float64
 10  Afeto Positivo                          2175 non-null   float64
 11  Afeto Negativo                          2183 non-null   float64
 12  Confiança no governo nacional           1838 non-null   float64
dtypes: float64(10), int64(1), object(2)
memory usage: 223.5+ KB

,Ano,Escada da Vida,Registrar PIB per capita,Apoio Social,Expectativa de vida saudável ao nascer,Liberdade para fazer escolhas de vida,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional
count,2199.000000,2199.000000,2179.000000,2186.000000,2145.000000,2166.000000,2126.000000,2083.000000,2175.000000,2183.000000,1838.000000
mean,2014.161437,5.479226,9.389766,0.810679,63.294583,0.747858,0.000096,0.745195,0.652143,0.271501,0.483999
std,4.718736,1.125529,1.153387,0.120952,6.901104,0.140150,0.161083,0.185837,0.105922,0.086875,0.193071
min,2005.000000,1.281271,5.526723,0.228217,6.720000,0.257534,-0.337527,0.035198,0.178886,0.082737,0.068769
25%,2010.000000,4.646750,8.499764,0.746609,59.119999,0.656528,-0.112116,0.688139,0.571684,0.207660,0.332549
50%,2014.000000,5.432437,9.498955,0.835535,65.050003,0.769821,-0.022671,0.799654,0.663063,0.260671,0.467140
75%,2018.000000,6.309460,10.373216,0.904792,68.500000,0.859382,0.092070,0.868827,0.737936,0.322894,0.618846
max,2022.000000,8.018934,11.663788,0.987343,74.474998,0.985178,0.702708,0.983276,0.883586,0.704590,0.993604

In [33]:
df_2.isna().sum()

Nome do país                                0
Indicador Regional                        112
Ano                                         0
Escada da Vida                              0
Registrar PIB per capita                   20
Apoio Social                               13
Expectativa de vida saudável ao nascer     54
Liberdade para fazer escolhas de vida      33
Generosidade                               73
Percepções de corrupção                   116
Afeto Positivo                             24
Afeto Negativo                             16
Confiança no governo nacional             361
dtype: int64

## Analisando as colunas

### Removendo as colunas dispensáveis

In [34]:
df_2 = df_2.drop(columns=['Indicador Regional'])
df_2

,Nome do país,Ano,Escada da Vida,Registrar PIB per capita,Apoio Social,Expectativa de vida saudável ao nascer,Liberdade para fazer escolhas de vida,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,NaN

### Renomeando as colunas

In [35]:
df_2 = df_2.rename(columns={
   'Nome do país': 'País',
   'Escada da Vida': 'Índice de Felicidade',
   'Registrar PIB per capita' : 'PIB per capita (US$)', 
   'Expectativa de vida saudável ao nascer': 'Expectativa de vida',
   'Liberdade para fazer escolhas de vida': 'Liberdade de escolhas',   
})
df_2

,País,Ano,Índice de Felicidade,PIB per capita (US$),Apoio Social,Expectativa de vida,Liberdade de escolhas,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,NaN

In [36]:
df_2.isna().sum()

País                               0
Ano                                0
Índice de Felicidade               0
PIB per capita (US$)              20
Apoio Social                      13
Expectativa de vida               54
Liberdade de escolhas             33
Generosidade                      73
Percepções de corrupção          116
Afeto Positivo                    24
Afeto Negativo                    16
Confiança no governo nacional    361
dtype: int64

### Preenchendo os dados NaN de cada país

In [37]:
for coluna in df_2.columns:
   if coluna != "País":
      df_2[coluna] = df_2.groupby("País")[coluna].transform(
         lambda x: x.fillna(x.mean())
      )

In [38]:
df_2.isna().sum()

País                               0
Ano                                0
Índice de Felicidade               0
PIB per capita (US$)               9
Apoio Social                       1
Expectativa de vida               32
Liberdade de escolhas              0
Generosidade                       9
Percepções de corrupção           29
Afeto Positivo                     2
Afeto Negativo                     1
Confiança no governo nacional    130
dtype: int64

In [39]:
df_2 = df_2.fillna(df_2.mean(numeric_only=True))

In [40]:
df_2.isna().sum()

País                             0
Ano                              0
Índice de Felicidade             0
PIB per capita (US$)             0
Apoio Social                     0
Expectativa de vida              0
Liberdade de escolhas            0
Generosidade                     0
Percepções de corrupção          0
Afeto Positivo                   0
Afeto Negativo                   0
Confiança no governo nacional    0
dtype: int64

In [41]:
df_2

,País,Ano,Índice de Felicidade,PIB per capita (US$),Apoio Social,Expectativa de vida,Liberdade de escolhas,Generosidade,Percepções de corrupção,Afeto Positivo,Afeto Negativo,Confiança no governo nacional
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,0.476866

In [42]:
# translator = Translator()
# cache = {}

# def traduzir_valor(v):
#     if v in cache:
#         return cache[v]
#     try:
#         t = translator.translate(str(v), src='en', dest='pt').text
#     except Exception:
#         t = v
#     cache[v] = t
#     return t

# coluna = "País"  # troque pelo nome da sua coluna
# df_2[coluna] = df_2[coluna].apply(traduzir_valor)

In [43]:
df_2.to_csv('../data/processed/world_happiness_report_colunas_pt_preprocessed.csv', index=False)